### ISSUE TITLE
Plan for a new release

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/yarp-telemetry#157]
Hi all, I was wondering if there is any plan to release a new version of library. It would be really useful in the context of the ANA Avatar Xprize.

cc @Nicogene @AlexAntn @traversaro @S-Dafarra

**Comment by Nicogene** [comment]
Hi @GiulioRomualdi !
Yes sure, I think we will do a release for the distro `2022.02.0`

**Comment by GiulioRomualdi** [comment]
Thank you very much!

**Comment by Nicogene** [comment]
The release has been done: https://github.com/robotology/yarp-telemetry/releases/tag/v0.4.0

Closing
