### ISSUE TITLE
app-logger: Proposal for a C++ library component to log channels per process

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp-telemetry#17]
This is an MVP proposal along the same line of robotology-playground/yarp-telemetry#15, inheriting many concepts and implementations from already available components such as [`MatLogger2`][1] and [`spdlog`][2].

I believe it can address the User Story proposed by @S-Dafarra in robotology-playground/yarp-telemetry#16. 

The fundamental idea is sketched out in these [slides](../blob/master/material/slides/app-logger.pptx). In the following, I'll only report on the main traits we'll be willing to discuss at the next periodic meetup.

The `app-logger` (feel absolutely free to suggest a better name) allows for:
- Doing logging for generic process pretty much as the `yarp-device-dumper` does for `yarprobotinterface`.
- We only deal with files as an available "sink" resources. In the future, we may consider extending the framework to deal with a further ethernet as a second possible sink.
- The logger component accumulates data into an internal circular buffer, which in turn gets flushed to the sink. The writing modes can cover the case of the last N bytes or N seconds or simply the entire history straight away.
- The API is very simple and enables the user to:
    - Configure the logger component at the process startup via a JSON file (JSON is better here than YAML as can be easily transferred through the network if we'll ever need it) that establishes what channels we aim to log, how to log them (asyn/sync), with which compression...
    - Acquire any variable (YARP types included) as a channel anywhere, meaning in any threads of the process. When we latch the variable, we attach to it a globally synched timestamp. The size of the variable can be determined at runtime at the very first latch and reported in the header of the log file.
- For logging purposes, a channel is further described by a bunch of information written in the JSON configuration file:
    - A unique ID. We should think of how to reduce the spread of information here.
    - The compression factor.
    - If it needs to be acquired asynchronously or sampled/downsampled at a specified rate.
- The log file can be MATIO compatible and needs to contain an initial header describing how the channels have been acquired and made available.

One of the chief peculiarities is that the user codebase can be written only once in terms of logging functionality including the calls to the latching function to be placed where we're required to draw off the channels. Then, the user is free to reconfigure the logger at will through the JSON file by deciding which channels to acquire and with which logging properties.

Open to discussions 🗣

[1]: https://github.com/ADVRHumanoids/MatLogger2
[2]: https://github.com/gabime/spdlog

cc:
- @icub-tech-iit/telemetry 
- $dic-iit/sw-dev
- $hsp-iit/sw-dev
- $edpr-iit/sw-dev

**Comment by diegoferigo** [comment]
cc @nunoguedelha
