### ISSUE TITLE
Discussion: new names for the repository and for the library

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarp-telemetry#172]
This issue is for gathering the name proposal for the new name of the repository, library, namespace.

cc @GiulioRomualdi

**Comment by Nicogene** [comment]
@Nicogene proposal:
- Repo : `robot-telemetry`
- Library: `robottelemetry`
- Namespace: `robottelemetry::`

**Comment by S-Dafarra** [comment]
@S-Dafarra proposal:
- Repo: ``robometry``
- Library: ``robometry``
- Namespace: ``robometry::``

**Comment by S-Dafarra** [comment]
@S-Dafarra proposal 2:
- Repo: ``robotemetry``
- Library: ``robotemetry``
- Namespace: ``robotemetry::``

**Comment by Nicogene** [comment]
> @S-Dafarra proposal:
> 
>     * Repo: `robometry`
> 
>     * Library: `robometry`
> 
>     * Namespace: `robometry::`

I am in favour of this since it is the only name not already present in GH -> https://github.com/search?q=robometry

**Comment by Nicogene** [comment]
@vtikha proposal:
- Repo : `robometrics`
- Library: `robometrics`
- Namespace: `robometrics::`

Repos with same name: https://github.com/search?q=robometrics
