### ISSUE TITLE
Discuss the possibility to remove YARP dependency from telemetery

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/yarp-telemetry#56]
Hi all, I was checking yarp telemetry. It would be great to embed it in [`bipedal-locomotion-framework`](https://github.com/dic-iit/bipedal-locomotion-framework) (aka `blf`). However, many libraries in `blf` do not depend on `YARP`. 

As far as I understood the only reason why `YARP` is used to have all the data synchronized with the same clock.

https://github.com/robotology-playground/yarp-telemetry/blob/306c9a047655fc65bf8072006193291bde767346/src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h#L75-L85

I theory this dependency can be easily dropped by passing a function to generate the clock. Thanks to this approach different kinds of clocks can be used. For instance `yarp clock`, `std clock`, `ros clock`).

The following patch implements what I proposed https://github.com/robotology-playground/yarp-telemetry/compare/master...GiulioRomualdi:remove/yarp_dependency

Looking forward to receiving your  feedback :smile: 

cc @traversaro @DanielePucci @S-Dafarra @Nicogene @AlexAntn

**Comment by Nicogene** [comment]
I personally like very much your implementation, besides removing the yarp dependency.

For now, yarp is used only for the clock but when the complexity will increase (e.g. handle and collect recording from different machines), yarp may become indispensable 

In any case, a PR with the changes you proposed is more than welcome!
